### ISSUE TITLE
Avoid duplicating dependencies in `requirements.in` AND `pyproject.toml`; Pyproject.toml is the future

### ISSUE THREAD

**Issue by lord-haffi** [Hochfrequenz/python_template_repository#145]
It is possible for `pip-tools` to compile the `requirements.txt` out of the `pyproject.toml` if the packaging tool is supported by the tool. Lucky us, that [hatch is indeed supported](https://github.com/jazzband/pip-tools#requirements-from-pyprojecttoml) by `pip-tools`.
Therefore, we don't need the "duplicate" `requirements.in` file anymore! Have fun, doing it in every repository ^^

@hf-kklein a great starter quest if you ask me :P

**Comment by hf-kklein** [comment]
good starter if pip-tools was working with python3.12 yet: https://github.com/jazzband/pip-tools/issues/2021

**Comment by lord-haffi** [comment]
> good starter if pip-tools was working with python3.12 yet: [jazzband/pip-tools#2021](https://github.com/jazzband/pip-tools/issues/2021)

😧 Well, I'm still using Python 3.11

**Comment by hf-kklein** [comment]
just because our newbies came with 3.12 installed and i want to save them the hazzle of re-configuring their toxbase to 3.11 when 3.12 is the better option in the long run.

**Comment by hf-kklein** [comment]
It works!
```
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile pyproject.toml
#

``` 
:)

**Comment by lord-haffi** [comment]
Don't know, what you want to do. I just wanted to get rid of the duplication. The dev_requirements are not listed in the pyproject.toml

**Comment by hf-kklein** [comment]
the we're done :)
